spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/flywaydemo?allowPublicKeyRetrieval=false&useSSL=true
    password: ThePassword
    username: springuser
#    driver-class-name: "com.mysql.jdbc.Driver"
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
#     This causes Hibernate to validate the schema to see if it
#     matches with what’s defined in Java. If no match is found,
#     the application will not start.
     ddl-auto: validate

#      Need this to create hibernate_sequence table, else direct validate fails.
#      Run this first and then the above one - ddl-auto: validate.
#      ddl-auto: update
  flyway:
#    custom table name  (default is flyway_schema_history)
    table: schema_version
    enabled: true